### ISSUE TITLE
편의성 문제 1개+오류 2개

### ISSUE THREAD

**Issue by MCPE-PC** [Astro36/Pugfolio#2]
```
Node.js: 8.5.0
NPM: 5.4.2
Installed via NVM
Kali GNU/Linux 2017.1 Rolling 32-bit(i386)
```
[사진 없음]
bin/index.js에 execute 권한이 기본적으로 존재하지 않아 `chmod +x bin/index.js`를 직접 입력해야 합니다.

![issue1pugfolio](https://user-images.githubusercontent.com/20432839/30518751-480d64be-9bc1-11e7-93e0-ab3c014295db.png)
(첫 실행 시 )output 파일명을 입력하지 않으면 중간에 멈춥니다. 1회 입력 시 삭제 전까지 정상 작동합니다. (첫 명령어로 `./bin/index.js examples/pugfolio.json`을 입력한다면 작동하지 않으며 `./bin/index.js examples/pugfolio.json index.html` 또는 `./bin/index.js examples/pugfolio.json output.html`처럼 파일명을 입력하면 이후 `./bin/index.js examples/pugfolio.json`이 정상적으로 작동합니다.)

![issue2pugfolio](https://user-images.githubusercontent.com/20432839/30518752-480da460-9bc1-11e7-88f3-5fcd793cf2a8.png)
pugfolio를 전역으로 설치 시 권한 오류가 발생합니다. 루트 권한을 부여해도 같습니다. puppeteer을 전역으로 설치하여 발생하는 것으로 확인되었습니다. (`npm i -g puppeteer`으로 확인하였습니다.)

**Comment by Astro36** [comment]
시험기간이여서 컴퓨터를 못 키고 폰코딩 중 입니다.
시험 끝나면 고칠 예정입니다.
버그 리포팅 감사합니다 :D
